# Generated by Django 6.0 on 2026-01-12 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_remove_theater_location_theater_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('action', 'Action'), ('comedy', 'Comedy'), ('drama', 'Drama'), ('thriller', 'Thriller'), ('horror', 'Horror'), ('romance', 'Romance'), ('biography', 'Biography'), ('animation', 'Animation')], max_length=20),
        ),
        migrations.AlterField(
            model_name='movie',
            name='trailer_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
