# Generated by Django 6.0 on 2026-01-26 15:32

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_seat_reserved_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
